apiVersion: v1
kind: Pod
metadata:
  name: code-server-shashwat
  labels:
    app: code-server
spec:
  containers:
  - name: code-server
    image: shasha0072/code-server-custom-extension:latest
    imagePullPolicy: IfNotPresent
    command: ["/usr/bin/entrypoint.sh"]
    args:
    - --cert=/certificates/cert.pem
    - --cert-key=/certificates/key.pem
    - --bind-addr=0.0.0.0:8443
    - --auth=password
    - /home/coder/workspace
    ports:
    - containerPort: 8443
    env:
    - name: PASSWORD
      value: "qwerty"
    volumeMounts:
    - name: config
      mountPath: /home/coder/.config
    - name: local-share
      mountPath: /home/coder/.local/share/code-server
    - name: workspace
      mountPath: /home/coder/workspace
    - name: certificates
      mountPath: /certificates
      readOnly: true
    securityContext:
      runAsUser: $(id -u shashwat | tr -d '\n')
      runAsGroup: $(id -g shashwat | tr -d '\n')
  volumes:
  - name: config
    hostPath:
      path: /home/shashwat/.config/code-server
      type: Directory
  - name: local-share
    hostPath:
      path: /home/shashwat/.local/share/code-server
      type: Directory
  - name: workspace
    hostPath:
      path: /mnt/syncstore/shashwat
      type: Directory
  - name: certificates
    hostPath:
      path: /opt/code-server/certificates
      type: Directory



    