apiVersion: v1
kind: Service
metadata:
  name: code-server-$USERNAME
  labels:
    app: code-server
    user: $USERNAME
spec:
  type: NodePort
  ports:
  - port: 8443
    targetPort: 8443
    nodePort: $PORT
  selector:
    app: code-server
    user: $USERNAME